[workspace.package]
authors = ["Mikuláš Bartáček"]
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "cli",
    "common",
    "compiler",
    "frontend",
    "typechecker",
    "vm",
]

[workspace.dependencies]
codespan-reporting = "0.13.1"
bincode = "2.0.1"

common = { path = "common" }
frontend = { path = "frontend" }
typechecker = { path = "typechecker" }
compiler = { path = "compiler" }
vm = { path = "vm" }
