[package]
name = "mluva"
authors = ["Mikuláš Bartáček"]
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "cli",
]

[dependencies]


[profile.dev]


[profile.release]
lto = true
opt-level = 3
debug = false
panic = "abort"