[package]
name = "mluva"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "cli",
]

[dependencies]


[profile.release]
lto = true
opt-level = 3
debug = false
panic = "abort"